### ISSUE TITLE
Help with usage of the ServiceExceptionErrorDecoder

### ISSUE THREAD

**Issue by moritzluedtke** [coveooss/feign-error-decoder#8]
We need a little help with using the ServiceExceptionErrorDecoder. We implemented all the classes mentioned in README.
But we struggle getting the constructor to work
We get the error:
`Parameter 0 of constructor ...ServiceExceptionErrorDecoderrequired a bean of type 'java.lang.Class' that could not be found.`

Can you provide us with an code example on how to use the ServiceExceptionErrorDecoderwith the Feign builder?

Thanks a lot!

### ApiPort 
```
public interface ApiPort {

    @PostMapping
    String request(@RequestHeader("SOAPAction") String soapAction, String body);

}
```

### Usage
```
ApiPort apiPort = Feign.builder()
                    .errorDecoder(errorDecoder)
                    .target(ApiPort.class, "http://to-some-destination:1234/api/somewhere");
```

**Comment by jebeaudet** [comment]
Can I see the source code of `ServiceExceptionErrorDecoder`? 

From what I can guess with the error message though, it seems like you have a `Class<?>` as an argument of your ServiceExceptionErrorDecoder class and you made it a bean, typically it'S used like this : 
```
ApiPort apiPort = Feign.builder()
                    .errorDecoder(new ServiceExceptionErrorDecoder(ApiPort.class))
                    .target(ApiPort.class, "http://to-some-destination:1234/api/somewhere");
```

**Comment by jebeaudet** [comment]
@moritzluedtke Any update on this?

**Comment by jebeaudet** [comment]
Closing due to lack of feedback
